// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Claw's DeFi Oracle - On-Chain Attestation Registry
/// @notice Records DeFi yield analyses and risk assessments as permanent on-chain attestations
/// @dev Built by Claw (AI agent) for The Synthesis Hackathon
contract ClawOracle {
    
    struct Attestation {
        string protocol;        // Protocol name (e.g. "Aave V3")
        string chain;           // Chain analyzed (e.g. "base")
        string asset;           // Asset analyzed (e.g. "USDC")
        uint256 apyBps;         // APY in basis points (420 = 4.20%)
        uint8 riskScore;        // 1-10 (10 = safest)
        string reasoningHash;   // IPFS CID of full analysis
        string decision;        // "RECOMMEND" | "CAUTION" | "AVOID"
        uint8 confidence;       // 0-100
        uint256 timestamp;      // Block timestamp
    }

    address public immutable agent;
    string public constant DISCLAIMER = "Generated by Claw, an AI agent. Not financial advice. DYOR.";
    
    Attestation[] public attestations;
    mapping(bytes32 => uint256) public latestForProtocol; // keccak(protocol) => attestation id + 1
    
    event AttestationRecorded(
        uint256 indexed id,
        string protocol,
        string asset,
        uint256 apyBps,
        uint8 riskScore,
        string decision
    );

    modifier onlyAgent() {
        require(msg.sender == agent, "Only Claw");
        _;
    }

    constructor() {
        agent = msg.sender;
    }

    /// @notice Record a new DeFi analysis attestation
    function record(
        string calldata protocol,
        string calldata chain,
        string calldata asset,
        uint256 apyBps,
        uint8 riskScore,
        string calldata reasoningHash,
        string calldata decision,
        uint8 confidence
    ) external onlyAgent returns (uint256 id) {
        require(riskScore >= 1 && riskScore <= 10, "Risk 1-10");
        require(confidence <= 100, "Conf 0-100");
        
        id = attestations.length;
        attestations.push(Attestation(
            protocol, chain, asset, apyBps,
            riskScore, reasoningHash, decision,
            confidence, block.timestamp
        ));

        latestForProtocol[keccak256(bytes(protocol))] = id + 1;
        
        emit AttestationRecorded(id, protocol, asset, apyBps, riskScore, decision);
    }

    /// @notice Get latest attestation for a protocol
    function latest(string calldata protocol) external view returns (Attestation memory) {
        uint256 idx = latestForProtocol[keccak256(bytes(protocol))];
        require(idx > 0, "No data");
        return attestations[idx - 1];
    }

    /// @notice Total attestation count
    function count() external view returns (uint256) {
        return attestations.length;
    }

    /// @notice Get attestation by ID
    function get(uint256 id) external view returns (Attestation memory) {
        require(id < attestations.length, "Invalid ID");
        return attestations[id];
    }
}
