#!/usr/bin/env node
/**
 * Claw's Full Autonomous Cycle
 * 
 * DISCOVER → PLAN → EXECUTE → VERIFY
 * 
 * 1. Scrape DeFi yields from DeFiLlama
 * 2. Analyze and score each protocol
 * 3. Record attestations on-chain
 * 4. Verify by reading back from chain
 * 
 * This is the "Let the Agent Cook" demo:
 * Complete autonomous decision loop with no human intervention.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const RESULTS_FILE = path.join(__dirname, '..', 'analysis-results.json');

async function main() {
  console.log('🏴‍☠️ CLAW\'S DEFI ORACLE - FULL AUTONOMOUS CYCLE');
  console.log('================================================');
  console.log(`Time: ${new Date().toISOString()}`);
  console.log('');

  // Phase 1: DISCOVER
  console.log('📡 Phase 1: DISCOVER');
  console.log('Scanning DeFi protocols on Base...');
  execSync(`node ${path.join(__dirname, 'analyze-yields.js')} --chain base --min-tvl 5000000 --top 15 --output ${RESULTS_FILE}`, {
    stdio: 'inherit'
  });
  console.log('');

  // Phase 2: PLAN (already done in analyze step - risk assessment)
  console.log('🧠 Phase 2: PLAN');
  const results = JSON.parse(fs.readFileSync(RESULTS_FILE));
  const recommended = results.filter(r => r.decision === 'RECOMMEND');
  const caution = results.filter(r => r.decision === 'CAUTION');
  const avoid = results.filter(r => r.decision === 'AVOID');
  console.log(`Analysis complete: ${recommended.length} RECOMMEND | ${caution.length} CAUTION | ${avoid.length} AVOID`);
  console.log('');

  // Phase 3: EXECUTE (record on-chain)
  console.log('⛓️  Phase 3: EXECUTE');
  if (!process.env.ORACLE_ADDRESS) {
    console.log('⚠️  No ORACLE_ADDRESS set. Skipping on-chain recording.');
    console.log('   Deploy first: npm run deploy:base-sepolia');
  } else {
    console.log('Recording attestations on-chain...');
    execSync(`npx hardhat run ${path.join(__dirname, 'record-attestation.js')} --network ${process.env.NETWORK || 'baseSepolia'} -- ${RESULTS_FILE}`, {
      stdio: 'inherit',
      env: { ...process.env }
    });
  }
  console.log('');

  // Phase 4: VERIFY
  console.log('✅ Phase 4: VERIFY');
  console.log(`Results file: ${RESULTS_FILE}`);
  console.log(`Total protocols analyzed: ${results.length}`);
  console.log(`Timestamp: ${new Date().toISOString()}`);
  
  // Top recommendation
  if (recommended.length > 0) {
    const best = recommended.sort((a, b) => {
      // Sort by risk score desc, then APY desc
      if (b.riskScore !== a.riskScore) return b.riskScore - a.riskScore;
      return b.apy - a.apy;
    })[0];
    console.log(`\n🏆 Top pick: ${best.protocol} on ${best.chain}`);
    console.log(`   ${best.asset} | APY: ${best.apy.toFixed(2)}% | Risk: ${best.riskScore}/10 | TVL: $${(best.tvl/1e6).toFixed(1)}M`);
  }

  console.log('\n⚠️  DISCLAIMER: Generated by Claw, an AI agent. Not financial advice. DYOR.');
  console.log('\n🏴‍☠️ Cycle complete. The Amulet grows stronger.');
}

main().catch(console.error);
